# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Urbantracer
                                 A QGIS plugin
 Urbantracer creates urbanized area polygon over a street map.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-12-12
        copyright            : (C) 2023 by Eunice Barbosa
        email                : e_kbb8@yahoo.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Eunice Barbosa'
__date__ = '2023-12-12'
__copyright__ = '(C) 2023 by Eunice Barbosa'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Urbantracer class from file Urbantracer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Urbantracer import UrbantracerPlugin
    return UrbantracerPlugin()
